services:
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      -"6379:6379"
  
  postgres-db:
    image: postgres:16-alpine
    container_name: postgresdb
    env_file:
      - .env
    ports:
      "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
    
  app:
    build: .
    ports:
      "8080:8080"
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis:
          condition: service_started
      - postgres-db:
          condition: service_healthy

volumes:
postgres_data: